export const SET_USER_DATA = 'scenes/Coins/Edit/set_user_data'
export const UPDATE_FORM_FIELD = 'scenes/Coins/Edit/update_form_field'
export const TOGGLE_MODAL = 'scenes/Coins/Edit/toggle_modal'
export const RESET_FORM = 'scenes/Coins/Edit/reset_form'
export const START_SEARCH = 'scenes/Coins/Edit/start_search'
